#%RAML 0.8
---
title: Test API specification
baseUri: http://localhost:3000/api/{version}
version: v1
# Resources
/books:
  get:
    description: Search for books by author, publication year, or rating
    queryParameters:
      author:
        displayName: Author
        type: string
        description: An author's full name
        example: Mary Roach
        required: false
      publicationYear:
        displayName: Publication Year
        type: number
        description: Original first-edition publication date of the book
        example: 1984
        required: false
      rating:
        displayName: Rating
        type: number
        description: Average rating (1-5) submitted by users
        example: 3.14
        required: false
  /{bookTitle}:
    get:
      description: Retrieve a specific book title
      queryParameters:
        isbn:
          displayName: ISBN
          type: string
          minLength: 10
          example: 0321736079?
      responses:
        200:
          body:
            application/json:
              example: |
                {
                  "data": {
                    "id": "0321736079?",
                    "title": "Stiff: the Curious Lives of Human Cadavers",
                    "description": null,
                    "datetime": 1341533193,
                    "genre": "science",
                    "author": "Mary Roach",
                    "link": "http://e-bookmobile.com/books/Stiff"
                  },
                  "success": true,
                  "status": 200
                }
    put:
      queryParameters:
        access_token:
          displayName: Access Token
          type: string
          description: OAuth 2.0 Access token
          required: true

